### ISSUE TITLE
mojom package still required for "getting started" instructions

### ISSUE THREAD

**Issue by abarth** [domokit/sky_engine#406]
```
name: hello_world
dependencies:
  sky: any 
  sky_tools: any 
  mojom: any
```

The `mojom` shouldn't be required but apparently was.
