### ISSUE TITLE
APK version mismatch causes mysterious crash

### ISSUE THREAD

**Issue by jimbeveridge** [domokit/sky_engine#454]
The Sky packages were updated today to 0.0.6. They were automatically updated in my dev environment when I did `pub upgrade`.

When I ran my Sky app, it crashed:

```
I/sky     (15954): Exception raised during _updatePaintingCanvas:
I/sky     (15954): Class 'Rect' has no instance method 'deflate'.
```

This happened because I did not do `sky_tool start --install`. However, it's not obvious when this command needs to be run, especially if I am switching between multiple devices.

There needs to be a way to validate that the installed version of sky_engine matches the build files so that the cause of an error like this is obvious.

Can this also happen to end-users? Should users be sent to the App Store to update?

**Comment by eseidelGoogle** [comment]
0.0.6 is from june:
https://pub.dartlang.org/packages/sky/versions

We definitely need to be better about warning users when the framework is
incompatible with the underlying engine however.

**Comment by jimbeveridge** [comment]
Eric and I looked at my machine and sky was the current version. Other modules were 0.0.6. Here's the list:

```
  sky:
    description: sky
    source: hosted
    version: "0.0.28"
  sky_engine:
    description: sky_engine
    source: hosted
    version: "0.0.6"
  sky_services:
    description: sky_services
    source: hosted
    version: "0.0.6"
  sky_tools:
    description: sky_tools
    source: hosted
    version: "0.0.6"
```
